version: '3.8'

services:
  torrent:
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 9091:9091
  media:
    user: 1000:1000
    ports:
      - 8096:8096

volumes:
  torrent-downloads:
    driver_opts:
      type: none
      o: bind
      device: ./.data/torrent_data
  torrent-cfg:
    driver_opts:
      type: none
      o: bind
      device: ./.data/torrent_cfg
  media-cfg:
    driver_opts:
      type: none
      o: bind
      device: ./.data/media_cfg
