name: Pipeline
on: 
  push: 
    branches:
     - '*'
env:
  REGISTRY_PREFIX: ghcr.io/${{github.repository}}
  IMG_TORRENT: linuxserver/transmission:amd64-latest
  IMG_MEDIA: jellyfin/jellyfin:latest
jobs:
  
  todos:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - run: make check-todos
  conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make check-conflicts
  gitflow:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'master')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make check-master

  test:
    runs-on: ubuntu-latest
    needs: [todos, conflicts]
    steps:
      - uses: actions/checkout@v2
      - run: |
          make release && cp .env.dist release/.env
          sed -i "s#DC_TORRENT_IMAGE=#DC_TORRENT_IMAGE=${REGISTRY_PREFIX}/#g" release/.env
          sed -i "s#DC_MEDIA_IMAGE=#DC_MEDIA_IMAGE=${REGISTRY_PREFIX}/#g" release/.env
      - run: echo "${{ secrets.ghcr_token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: |
          cd release && make run logs && sleep 15
          docker-compose ps --all
      - uses: actions/upload-artifact@v2
        with:
          name: compose-logs
          path: |
            release/.env
            release/compose.log
          retention-days: 1
      - run: |
          cd release && docker-compose ps torrent | grep Up
          docker-compose logs torrent | grep -E "Transmission [0-9.]+ \(.+?\) started"
      - run: |
          cd release && docker-compose ps media | grep Up
          docker-compose logs media | grep "Main: Startup complete"
      - run: cd release && docker-compose down --remove-orphans
