name: Release

on:
  release:
    types: [created]

jobs:
  - id: get_release
    uses: bruceadams/get-release@v1.2.2
    env:
      GITHUB_TOKEN: ${{ github.token }}
  - uses: actions/checkout@v2
  - run: make release BUILD_VERSION=${{github.ref}}
  - uses: actions/upload-release-asset@v1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      upload_url: ${{ steps.get_release.outputs.upload_url }}
      asset_path: ./hms-${{github.ref}}.zip
      asset_name: hms-${{github.ref}}.zip
      asset_content_type: application/zip
