name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: bruceadams/get-release@v1.2.2
        id: get_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/checkout@v2
      # - run: make release BUILD_VERSION=${GITHUB_REF##*/}
      - run: make release BUILD_VERSION=release
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./hms-release.zip
          asset_name: hms-${GITHUB_REF##*/}.zip
          asset_content_type: application/zip
